### ISSUE TITLE
i cant click on map pin

### ISSUE THREAD

**Issue by rincethomas33** [Monits/blackberry-commons#1]
[Blackberry Java]  -  i am using touch device. when i click, nothing is happening. when i double click, then map pin is getting focus. how to give focus, when i single click the map pin ?

**Comment by jsotuyod** [comment]
Hi, thanks for using our library.

My best guess is that you are not compiling with touch support. Our library support Blackberry OS 4.6+, and such old versions did not support touch events (which where added in 4.7.0).

To support both flavors, our library uses conditional compilation. In particular, we use the variable `TouchEnabled` to include / filter touch-related code, as [can be seen here](https://github.com/Monits/blackberry-commons/blob/master/src/com/monits/blackberry/commons/uielements/CustomMap.java#L204). Without that definition, touch will be disabled.

You can read more about the preprocessor and how to configure such directives to include / exclude pieces of code [here](http://berrytutorials.blogspot.com.ar/2009/11/coding-for-multiple-blackberry-devices.html)

Please let me know if this solves this issue, so I can close it and add proper clarifications to the `README`.

**Comment by rincethomas33** [comment]
hi, when i double tap on the pin(blackberry 9850 touch device), then only its getting focus. after that i have to click the trackball. then it will show the details of the pin. when i click the tap on the pin, nothing is happening.

**Comment by jsotuyod** [comment]
Can you please confirm you have set the `TouchEnabled` definition for the preprocessor?

**Comment by rincethomas33** [comment]
yes . its added. 
//#ifdef TouchEnabled
import net.rim.device.api.ui.TouchEvent;
import net.rim.device.api.ui.TouchGesture;
//#endif

**Comment by jsotuyod** [comment]
That's on the code, but you need to define it on the project properties:

![Project properties example](http://3.bp.blogspot.com/_yfmvW2iZYd8/SwG-XxX8AKI/AAAAAAAAAa4/pv9CNraFwMY/s400/projectproperties.png)

Just as `JDE_4_7_0` is defined there, you need to define `TouchEnabled`

**Comment by rincethomas33** [comment]
when i check the project properties, its showing like below. 
![img](https://cloud.githubusercontent.com/assets/1272569/7110056/a8a22aae-e1c8-11e4-982f-525df3f3f54c.JPG)
there is no compile tab.

**Comment by jsotuyod** [comment]
What's on your application's descriptor?

**Comment by rincethomas33** [comment]
there are 3 tabs on my application's descriptor
![build](https://cloud.githubusercontent.com/assets/1272569/7110242/b4ce0b56-e1cb-11e4-8a90-36a1a1d83e93.JPG)
![alternative](https://cloud.githubusercontent.com/assets/1272569/7110243/b4d0c846-e1cb-11e4-9f3d-cac030fe37aa.JPG)
![app](https://cloud.githubusercontent.com/assets/1272569/7110241/b4cc45fa-e1cb-11e4-9576-9b6e60770526.JPG)

**Comment by jsotuyod** [comment]
Right there on the first one. Bottom left it says "Preprocessor Directives", click on "Add...", add `TouchEnabled` and make sure it's checked as Active.

**Comment by rincethomas33** [comment]
ok. thanks dear friend........ its working now. Thanks a ton........

**Comment by rincethomas33** [comment]
in your post mention this too. so it will be helpful to all developers.

**Comment by jsotuyod** [comment]
Glad it worked, I'll make sure to update the docs and README with this info.

**Comment by rincethomas33** [comment]
one more doubt- if i am using non touch devices, then how user will know which one gets focus ?

**Comment by jsotuyod** [comment]
The `CustomMap` constructor takes a `Bitmap` as a parameter, which is meant to be used as a crosshair to show trackpad-based devices where they would be clicking.

In [this example](https://github.com/Monits/blackberry-commons/wiki/CustomMap) we are using a blue round crosshair. The crosshair is always in the middle of the map. When you move the trackpad, the map moves around. Once you place the crosshair over a marker, you can click to open it.

**Comment by rincethomas33** [comment]
map is not scrolling on non touch devices. when i scroll the trackball, its not moving.

**Comment by jsotuyod** [comment]
It won't by default, check the example I talked about before. The code to have it scroll is in there.

**Comment by rincethomas33** [comment]
i added the code of key down and repeat. still its not scrolling. i have to add anything else?. zoom in and zoom out is working(using keys "o" and "i")

**Comment by jsotuyod** [comment]
No, nothing else should be needed... make sure the MapField ha focus and it should scroll...

**Comment by rincethomas33** [comment]
its like something is holding map back :P  still its not scrolling

**Comment by rincethomas33** [comment]
this is my code. https://drive.google.com/file/d/0B-LiA_ra-p02TjJjZ0JjcXBhc2M/view?usp=sharing

**Comment by rincethomas33** [comment]
did you find any errors in my code? or what i am doing wrong there ?
